### ISSUE TITLE
pypi securitybot

### ISSUE THREAD

**Issue by brifordwylie** [dropbox/securitybot#15]
Super great project, thanks so much for releasing it open source. I was going to spin up one of my own but it's clear this project is WAY better than mine would have ever been. So related to that, I'm happy to give you the pypi 'securitybot' project (https://pypi.python.org/pypi/securitybot). Just email me at briford@supercowpowers.com and we'll setup the 'switch'. :)

**Comment by lfaraone** [comment]
Done! We'll probably merge in a few PRs before actually uploading a first release.

Thanks again!
